version: "3"

services:

  postgres:
    container_name: local-postgres
    image: postgres:12.6
    ports:
      - 5432:5432
    hostname: postgres
    environment:
      - PGDATABASE=pokemon
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password